
language: php

dist: xenial

git:
  depth: 2

addons:
  apt_packages:
    - parallel
    - language-pack-fr-base
    - zookeeperd
    - libzookeeper-mt-dev

env:
  global:
    - MIN_PHP=7.4
    - SYMFONY_PROCESS_PHP_TEST_BINARY=~/.phpenv/shims/php
    - SYMFONY_PHPUNIT_DISABLE_RESULT_CACHE=1
    - SYMFONY_VERSION="5.1.*" DB=mysql
    - APP_ENV=test

matrix:
  include:
    - php: 7.4
      env: deps=high
      services: [memcached]
  fast_finish: true
  allow_failures:
    - php: 8.0snapshot
      services: [memcached]

cache:
  directories:
    - .phpunit
    - php-$MIN_PHP
    - ~/php-ext

before_install:

install:
  - composer install --no-interaction
  - cp .env .env.test
  - php bin/console doctrine:database:create --env=test --no-interaction
  - php bin/console doctrine:migrations:migrate --env-test --no-interaction

script:
  - phpunit

services:
  - mysql