
language: php

dist: xenial

services:
  - mysql

env:
  global:
    - MIN_PHP=7.4
    - SYMFONY_PROCESS_PHP_TEST_BINARY=~/.phpenv/shims/php
    - SYMFONY_PHPUNIT_DISABLE_RESULT_CACHE=1
    - SYMFONY_VERSION="5.2.*" DB=mysql
    - APP_ENV=test
    
matrix:	
  include:	
    - php: 7.4	
      env: deps=high	
      services: [memcached]	
  fast_finish: true	
  allow_failures:	
    - php: 8.0snapshot	
      services: [memcached]	

cache:	
  directories:	
    - .phpunit	
    - php-$MIN_PHP	
    - ~/php-ext
    
before_install:
  - sudo systemctl start mysql
  - mysql -e 'create database foo;'

install:
  - composer install --no-interaction
  - cp .env .env.test
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:migrations:migrate --env=test --no-interaction
  
script:
  - phpunit

